spring:
  application:
    name: Hell-Study

  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        timezone:
          default_storage: NORMALIZE
    open-in-view: false
